[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2ecc71"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#1a1a2e"
font = "sans serif"
# Last updated: Thu Feb 19 16:00:09 IST 2026
